export default [
  'patrimonio',
  'numero_serie',
  'marca',
  'modelo',
  'tipo_ht',
  'unidade',
  'status_operacional',
  'local_atual',
  'equipe_vinculada',
  'viatura_vinculada',
  'qr_code',
  'foto_url',
  'ativo',
  'observacoes'
]
export default [
  'patrimonio',
  'numero_serie',
  'marca',
  'modelo',
  'tipo_ht',
  'unidade',
  'status_operacional',
  'local_atual',
  'equipe_vinculada',
  'viatura_vinculada',
  'qr_code',
  'foto_url',
  'ativo',
  'observacoes'
]