export const MODULOS_AGENDA = {
  TONFAS: 'TONFAS',
  ARMAS: 'ARMAS',
  HT: 'HT',
  TPD: 'TPD',
  COLETES: 'COLETES',
  MUNICOES: 'MUNICOES',
  VIATURAS: 'VIATURAS',
  DOCUMENTOS: 'DOCUMENTOS',
  OUTROS: 'OUTROS'
}

export const EVENTOS_AGENDA = {
  DEVOLUCAO: 'DEVOLUCAO',
  MANUTENCAO: 'MANUTENCAO',
  REVISAO: 'REVISAO',
  INSPECAO: 'INSPECAO',
  VALIDADE: 'VALIDADE',
  OUTRO: 'OUTRO'
}

export const STATUS_AGENDA = {
  ATIVO: 'ATIVO',
  ENCERRADO: 'ENCERRADO',
  VENCIDO: 'VENCIDO',
  CANCELADO: 'CANCELADO'
}

export const ALERTAS_AGENDA = {
  NENHUM: 'NENHUM',
  ALERTA_48H: '48H',
  ALERTA_24H: '24H',
  VENCIMENTO: 'VENCIMENTO'
}

export const DESTINATARIOS_AGENDA = {
  P4: 'P4',
  ENCARREGADO_SVDD: 'ENCARREGADO DO SVDD',
  COMANDANTE_CIA: 'COMANDANTE DE CIA',
  ADMINISTRADOR: 'ADMINISTRADOR'
}
