export const PERFIS = {
  ADMINISTRADOR: 'ADMINISTRADOR',

  COMANDANTE_CIA: 'COMANDANTE DE CIA',

  P4: 'P4',

  ENCARREGADO_SVDD: 'ENCARREGADO DO SVDD',

  AUXILIAR_SVDD: 'AUXILIAR DO SVDD',

  USUARIO: 'USUÁRIO'
}

export const PERFIS_GESTAO_PATRIMONIAL = [
  PERFIS.ADMINISTRADOR,
  PERFIS.COMANDANTE_CIA,
  PERFIS.P4,
  PERFIS.ENCARREGADO_SVDD,
  PERFIS.AUXILIAR_SVDD
]