import { useMemo, useState } from 'react'

function dataHora(valor) { if (!valor) return '—'; const data = new Date(valor); return Number.isNaN(data.getTime()) ? '—' : new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(data) }

export default function HTAprovacoesModal({ aberto, itens = [], podeDecidir = false, processandoId = null, onClose, onDecidir }) {
  const [busca, setBusca] = useState('')
  const filtrados = useMemo(() => { const t = busca.trim().toUpperCase(); return !t ? itens : itens.filter((i) => [i.patrimonio,i.numero_serie,i.motivo,i.solicitada_por_nome].some((v)=>String(v||'').toUpperCase().includes(t))) }, [itens,busca])
  if (!aberto) return null
  return <div className="ht-modal-backdrop" role="presentation" onMouseDown={(e)=>e.target===e.currentTarget&&!processandoId&&onClose()}><section className="ht-approval-modal"><header><div><span>Fluxo hierárquico</span><h2>Aguardando aprovações</h2><p>Solicitações de baixa patrimonial pendentes de decisão.</p></div><button type="button" onClick={onClose}>×</button></header><div className="ht-approval-body"><input type="search" value={busca} onChange={(e)=>setBusca(e.target.value)} placeholder="Pesquisar patrimônio, motivo ou solicitante"/><div className="ht-approval-list">{filtrados.length===0?<div className="ht-transfer-empty">Nenhuma solicitação pendente.</div>:filtrados.map((item)=><article key={item.id}><div className="ht-approval-copy"><strong>{item.patrimonio||item.numero_serie||'HT'}</strong><span>{item.motivo}</span><small>Solicitado por {item.solicitada_por_nome||'SIGMO'} em {dataHora(item.solicitada_em)}</small><p>{item.observacoes}</p>{item.fotos?.length>0&&<div className="ht-approval-photos">{item.fotos.map((foto)=><a key={foto.id} href={foto.foto_url} target="_blank" rel="noreferrer"><img src={foto.foto_url} alt="Evidência da baixa"/></a>)}</div>}</div>{podeDecidir&&<div className="ht-approval-actions"><button type="button" onClick={()=>onDecidir(item,'APROVAR')} disabled={Boolean(processandoId)}>Aprovar</button><button type="button" onClick={()=>onDecidir(item,'DILIGENCIA')} disabled={Boolean(processandoId)}>Diligência</button><button type="button" className="danger" onClick={()=>onDecidir(item,'REPROVAR')} disabled={Boolean(processandoId)}>Reprovar</button></div>}</article>)}</div></div><footer><span>{filtrados.length} pendente(s)</span><button type="button" className="ht-btn-secondary" onClick={onClose}>Fechar</button></footer></section></div>
}
