export const TIPOS_MOVIMENTACAO = Object.freeze({
  CAUTELA: 'CAUTELA',
  DEVOLUCAO: 'DEVOLUÇÃO',
  TRANSFERENCIA: 'TRANSFERÊNCIA',
  BAIXA: 'BAIXA',
  ENTREGA: 'ENTREGA'
})

export const STATUS_MOVIMENTACAO = Object.freeze({
  RASCUNHO: 'RASCUNHO',
  PENDENTE: 'PENDENTE',
  APROVADA: 'APROVADA',
  RECUSADA: 'RECUSADA',
  CONCLUIDA: 'CONCLUÍDA',
  CANCELADA: 'CANCELADA'
})

export const LOCAL_DESTINO_PADRAO =
  'CAUTELA INDIVIDUAL'

export const LOCAIS_DESTINO = [
  'CAUTELA INDIVIDUAL',
  'P4',
  '1ª CIA',
  '2ª CIA',
  '3ª CIA',
  'ARMARIA',
  'RESERVA DE MATERIAL'
]