export { default as PatrimonioPage } from './PatrimonioPage'
export { default as PatrimonioForm } from './PatrimonioForm'
export { default as PatrimonioDetails } from './PatrimonioDetails'
export { default as PatrimonioFotos } from './PatrimonioFotos'
export { default as PatrimonioQRCode } from './PatrimonioQRCode'
export { default as PatrimonioMovimentacoes } from './PatrimonioMovimentacoes'